auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: debug

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /home/ubuntu/erp-backend/var/loki/index
    cache_location: /home/ubuntu/erp-backend/var/loki/index_cache
    compactor_directory: /home/ubuntu/erp-backend/var/loki/compactor

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  allow_structured_metadata: false

chunk_store_config:

compactor:
  working_directory: /var/loki/compactor

table_manager:
  retention_deletes_enabled: true