server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "spring-boot-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "spring-boot"
          __path__: "/app/logs/*.log"