global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']
        labels:
          service: 'spring-boot'
          instance: 'api'

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          instance: 'postgres-exporter'

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
        labels:
          service: 'logs'
          instance: 'promtail'