name: Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run Docker Compose
        env:
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SECURITY_USER_NAME: ${{ secrets.SECURITY_USER_NAME }}
          SECURITY_USER_PASSWORD: ${{ secrets.SECURITY_USER_PASSWORD }}
          jwtSecret: ${{ secrets.jwtSecret }}
        run: |
          docker compose up --build