global:
  scrape_interval: 5s  # Coleta métricas a cada 5 segundos

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']