global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['18.118.195.205:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['erp-backend-postgres-exporter:9187']